version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_acute_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_any_acute_covid_pri_care
    outputs:
      highly_sensitive:
        cohort: output/input_any_acute_covid_pri_care.csv
        
  generate_og_pc_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ongoing_post_covid
    outputs:
      highly_sensitive:
        cohort: output/input_ongoing_post_covid.csv

  debug_cohort:
    run: r:latest analysis/debug_script.R
    needs: [generate_acute_cohort, generate_og_pc_cohort]
    outputs:
      moderately_sensitive:
        debug_oc: output/debug_oc.csv
        debug_ac: output/debug_ac.csv

  describe:
    run: r:latest analysis/report.R
    needs: [generate_acute_cohort, generate_og_pc_cohort]
    outputs:
      moderately_sensitive:
        pc_counts: output/ratios.csv