version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_acute_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_any_acute_covid_pri_care
    outputs:
      highly_sensitive:
        cohort: output/input_any_acute_covid_pri_care.csv
        
  generate_og_pc_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ongoing_post_covid
    outputs:
      highly_sensitive:
        cohort: output/input_ongoing_post_covid.csv
        
  generate_cohort_all:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_all
    outputs:
      highly_sensitive:
        cohort: output/input_all.csv

  debug_cohorts:
    run: r:latest analysis/debug_script.R
    needs: [generate_acute_cohort, generate_og_pc_cohort, generate_cohort_all]
    outputs:
      moderately_sensitive:
        debug_oc: output/debug_oc_counts.csv
        debug_ac: output/debug_ac_counts.csv
        debug_all_counts: output/debug_all_counts.csv
        debug_all_crosstab: output/debug_all_diag_refer_crosstab.csv

  compliance_ratios:
    run: r:latest analysis/guideline_compliance_ratios.R
    needs: [generate_acute_cohort, generate_og_pc_cohort, generate_cohort_all]
    outputs:
      moderately_sensitive:
        pc_counts: output/ratios.csv
        ref_rates: output/ref_rates_by_month.csv
        
  descriptive_coding_script:
    run: r:latest analysis/descriptive_coding_script.R
    needs: [generate_cohort_all]
    outputs:
      moderately_sensitive:
        Fig1: output/Fig_1.png
        Fig1_numbers: output/Fig_1_numbers.csv
        Fig2: output/Fig_2.png
        Fig3: output/Fig_3.png
        Table_1: output/Table_1.csv
        Table_2: output/Table_2.csv
        Table_3: output/Table_3.csv


  HE_compliance_summary:
    run: r:latest analysis/HE_compliance_summary.R
    needs: [generate_acute_cohort]
    outputs:
      moderately_sensitive:
        HE_summary_table_1_1: output/monthly_summary_tab_1_1.csv
        HE_summary_fig_1_1_age: output/line_chart_1_1_age_group.png
        HE_summary_fig_1_1_eth: output/line_chart_1_1_ethnicity.png
        HE_summary_fig_1_1_IMD: output/line_chart_1_1_imd.png
        HE_summary_fig_1_1_region: output/line_chart_1_1_region.png
        HE_summary_fig_1_1_sex: output/line_chart_1_1_sex.png
        HE_summary_fig_1_1_total: output/line_chart_1_1_total.png
        HE_summary_table_1_8: output/monthly_summary_tab_1_8.csv
