version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_acute_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_any_acute_covid_pri_care
    outputs:
      highly_sensitive:
        cohort: output/input_any_acute_covid_pri_care.csv
        
  generate_og_pc_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ongoing_post_covid
    outputs:
      highly_sensitive:
        cohort: output/input_ongoing_post_covid.csv
        
  generate_cohort_all:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_all
    outputs:
      highly_sensitive:
        cohort: output/input_all.csv

  debug_cohorts:
    run: r:latest analysis/debug_script.R
    needs: [generate_acute_cohort, generate_og_pc_cohort, generate_cohort_all]
    outputs:
      moderately_sensitive:
        debug_oc: output/debug_oc_counts.csv
        debug_ac: output/debug_ac_counts.csv
        debug_all_counts: output/debug_all_counts.csv
        debug_all_crosstab: output/debug_all_diag_refer_crosstab.csv

  compliance_ratios:
    run: r:latest analysis/guideline_compliance_ratios.R
    needs: [generate_acute_cohort, generate_og_pc_cohort, generate_cohort_all]
    outputs:
      moderately_sensitive:
        pc_counts: output/ratios.csv
        ref_rates: output/ref_rates_by_month.csv
        
  descriptive_coding_script:
    run: r:latest analysis/descriptive_coding_script.R
    needs: [generate_cohort_all]
    outputs:
      moderately_sensitive:
        ac_to_lc: output/ac_to_lc.png
        og_dest: output/og_destination.png
        pc_dest: output/pc_destinations.png
        time_acute_to_lc: output/mean_diff_to_days.csv
        freq_table: output/freq_table.csv