version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_og_pc_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ongoing_post_covid
    outputs:
      highly_sensitive:
        cohort: output/input_ongoing_post_covid.csv
        
  describe:
    run: r:latest analysis/report.R
    needs: [generate_og_pc_cohort]
    outputs:
      moderately_sensitive:
        pc_counts: output/PC_count_table.csv